name: PR Build & E2E Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  # push:
  #  branches: [ develop ]
  pull_request:
    branches: [develop]

  # # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: 18.x

      - name: Cache node modules
        uses: actions/cache@main
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: |
            ~/.cache/Cypress
            node_modules
          key: v1-dependencies--${{ hashFiles('package.json') }}

      - name: Install Dependencies
        run: npm i -g pnpm

      - run: pnpm install

      - run: pnpm build

      - run: pnpm start & sleep 3; pnpm test:e2e
      # # - run: npm run test